[username]
format = "[$user]($style)"
style_user = "bold blue"
show_always = true

[hostname]
format = "@[$hostname]($style) "
style = "bold dimmed green"
ssh_only = false

[directory]
style = "purple"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "green"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "red"

[package]
disabled = true

# Simple prompt character
[character]
success_symbol = "[λ ](bold red)"
error_symbol = "[× ](bold red)"
