theme = "catppuccin_mocha"
# Theme must be the first line in the config for the switcher to work

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
# Code runners
C-r = { j = ":sh javac Main.java -Xlint:unchecked; java Main", r = ":sh cargo run" }

# Window manipulation
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"